apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoat-bridge.fullname" . }}
  labels:
    {{- include "stoat-bridge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stoat-bridge.selectorLabels" . | nindent 4 }}
